#!/bin/bash

set -e
reg=${DOCKER_REGISTRY:-''}
VERSION=${VERSION:-${BUILD_NUMBER:-$(date '+%Y%m%d%H%M%S')}}

build_tag_push() {
	dir=$1; shift;
	test -d $dir || {
		echo ERROR: $dir is not a directory
		exit 2
	}
	pushd $dir > /dev/null
	test -f Dockerfile && {
		dir=$(basename $PWD)
       		img=cslauritsen/$dir
		echo Building image $img from $PWD
		docker build -t $img $BUILD_ARGS .
       		docker tag $img $img
        	docker tag $img $img:$VERSION
        	docker push $img:latest
        	docker push $img:$VERSION
	}
	popd > /dev/null
}

if [[ -d containers ]]
then
	echo using subdirectories of '"containers"'
	pushd containers > /dev/null
	for dir in *
	do
		build_tag_push $dir
	done
else
	if [[ -d $1 ]]
	then
		build_tag_push $1
	else
		echo ERROR: No "'containers'" directory in $PWD, 
		echo neither did you not specify a directory to build from. 
		echo Usage
		echo   $0 '<directory>'
		exit 1
	fi
	popd > /dev/null
fi


echo Tagged with version $VERSION
