apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: justsotech-staging-cert
  namespace: jst
spec:
  secretName: justsotech-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: justsotech.com
  dnsNames:
  - justsotech.com