apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: justsotech-prod-cert
  namespace: jst
spec:
  secretName: justsotech-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: justsotech.com
  dnsNames:
  - justsotech.com