---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: jst
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-site
  namespace: jst
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # Tell traefik to use HTTP to talk to the backend
    ingress.kubernetes.io/protocol: http
#   traefik.ingress.kubernetes.io/router.middlewares: jst-redirect-https@kubernetescrd
spec:
  tls:
  - hosts:
    - justsotech.com
    secretName: justsotech-prod-tls
  rules:
    - host: justsotech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: static-site
                port: 
                  name: http